variables:
  TEST_IMAGE: "node:14-alpine"
  BUILD_IMAGE: "gitlab.paymoapp.com:5555/envscripts/img-ubuntu-base"
  ADDON_BUILD_IMAGE: "gitlab.paymoapp.com:5555/envscripts/img-ubuntu-widget-build"

# Mixins
.only_any_v_tags:
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/
  except:
    - branches

.only_release_v_tags:
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
  except:
    - branches

.job_test:
  image: $TEST_IMAGE
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
  before_script:
    - npm ci --ignore-scripts

.job_build_addon:
  stage: build-addon
  before_script:
    - npm ci --ignore-scripts
  script:
    - npm run build:gyp
    - npm run publish:bindings
  needs:
    - lint
    - typecheck

stages:
  - test
  - build-addon
  - publish

# Test stage
lint:
  extends:
    - .job_test
  script:
    - npm run lint

typecheck:
  extends:
    - .job_test
  script:
    - npm run typecheck

# Build-addon stage
build-addon-windows:
  extends:
    - .only_any_v_tags
    - .job_build_addon
  tags:
    - win
  before_script:
    - npm config set msvs_version 2022
    - npm ci --ignore-scripts

build-addon-mac-x64:
  extends:
    - .only_any_v_tags
    - .job_build_addon
  tags:
    - osx
  script:
    - npm run build:gyp:configure -- --target_arch=x64
    - npm run build:gyp:run -- --target_arch=x64
    - npm run publish:bindings -- --target_arch=x64

build-addon-mac-arm64:
  extends:
    - .only_any_v_tags
    - .job_build_addon
  tags:
    - osx
  script:
    - npm run build:gyp:configure -- --target_arch=arm64
    - npm run build:gyp:run -- --target_arch=arm64
    - npm run publish:bindings -- --target_arch=arm64

build-addon-linux:
  extends:
    - .only_any_v_tags
    - .job_build_addon
  image: $ADDON_BUILD_IMAGE

# Publish stage
build-library:
  extends:
    - .only_any_v_tags
  image: $BUILD_IMAGE
  stage: publish
  before_script:
    - npm ci --ignore-scripts
  script:
    - npm run build:ts
    - npm set @paymo:registry https://gitlab.paymoapp.com/api/v4/projects/$CI_PROJECT_ID/packages/npm/
    - npm set //gitlab.paymoapp.com/api/v4/projects/$CI_PROJECT_ID/packages/npm/:_authToken $CI_JOB_TOKEN
    - npm publish
    # - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
    # - npm publish
    - LAST_RELEASE="$(git describe --abbrev=0 --tags ${CI_COMMIT_TAG}^)"
    - CHANGELOG="$(git diff -U0 $LAST_RELEASE $CI_COMMIT_TAG CHANGELOG.md | grep -E "^\+" | grep -vE "^\+\+\+" | sed "s/^\+//")"
    - >
      curl -sSL -X POST -H "JOB-TOKEN: $CI_JOB_TOKEN" -H "Content-type: application/json" -d "{ \"name\": $(echo $CI_COMMIT_TAG | jq -Ra .), \"tag_name\": $(echo $CI_COMMIT_TAG | jq -Ra .), \"description\": $(echo $CHANGELOG | jq -Rsa .) }" ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases
  artifacts:
    paths:
      - dist
    expire_in: 12h
  needs:
    - lint
    - typecheck
