name: Build native modules

on:
    push:
        tags: ['v*'] # Trigger on version tags

jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: macos-13
                      arch: x64
                      platform: darwin
                    - os: macos-13-xlarge # as of january 2024, macos-13-xlarge is the only true apple silicon arm64 github hosted macos runner available
                      arch: arm64
                      platform: darwin
                    - os: windows-latest
                      arch: x64
                      platform: win32
                    - os: windows-11-arm
                      arch: arm64
                      platform: win32
        runs-on: ${{ matrix.os }}
        name: ${{ matrix.platform }}-${{ matrix.arch }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install Python Distutils (Not Mac OS - Latest)
              if: ${{ !contains(matrix.os, 'macos-13-xlarge') }}
              run: |
                  python3 -m pip install setuptools

            - name: Install Python Distutils (Mac OS - Latest)
              if: contains(matrix.os, 'macos-13-xlarge')
              run: |
                  brew install python-setuptools

            - name: Install dependencies
              run: |
                  npm install -g cross-env
                  npm install --ignore-scripts

            - name: Build native module
              run: npm run build:ci
              env:
                  ARCH: ${{ matrix.arch }}
                  npm_config_arch: ${{ matrix.arch }}
                  npm_config_target_arch: ${{ matrix.arch }}

            - name: Run prebuild
              run: npm run prebuild -- --strip
              env:
                  ARCH: ${{ matrix.arch }}
                  npm_config_arch: ${{ matrix.arch }}
                  npm_config_target_arch: ${{ matrix.arch }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: active-window-${{ github.ref_name }}-napi-v6-${{ matrix.platform }}-${{ matrix.arch }}
                  path: prebuilds/

    create-release:
        needs: build
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: all-artifacts

            - name: Create Release with Artifacts
              uses: ncipollo/release-action@v1
              with:
                  artifacts: 'all-artifacts/**/*'
                  draft: false
                  prerelease: false
                  generateReleaseNotes: true
                  token: ${{ secrets.GITHUB_TOKEN }}
